### ISSUE TITLE
coremltools 4.1 and pytorch 1.7 apparently incompatible

### ISSUE THREAD

**Issue by iutlu** [conda-forge/coremltools-feedstock#12]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

coremltools 4.1 conda-forge packages seem to require `pytorch <1.7`.

As such, the following fails
`conda create -n test python=3.8 pytorch=1.7 coremltools=4.1 -c pytorch -c conda-forge`,
while this succeeds
`conda create -n test python=3.8 pytorch=1.6 coremltools=4.1 -c pytorch -c conda-forge`.

This is curious since coremltools 4.1 release notes specifically [advertise](https://github.com/apple/coremltools/releases/tag/4.1) pytorch 1.7 support.

I suspect `pytorch <1.7` might be a leftover constraint from previous releases -- would appreaciate if you could look into this -- thanks!

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : pytorch
    active env location : /mnt/pixery/miniconda3/envs/pytorch
            shell level : 1
       user config file : /home/ubuntu/.condarc
 populated config files : /home/ubuntu/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __cuda=10.2=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /mnt/pixery/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /mnt/pixery/miniconda3/pkgs
                          /home/ubuntu/.conda/pkgs
       envs directories : /mnt/pixery/miniconda3/envs
                          /home/ubuntu/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.8.5 Linux/4.15.0-1060-aws ubuntu/18.04.3 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by seibert** [comment]
Good catch.  I will remove the version constraint.

**Comment by seibert** [comment]
The recipe has been fixed.  New build should appear on conda forge in a little while.

**Comment by iutlu** [comment]
Thanks!

**Comment by iutlu** [comment]
Hello again! I was wondering when I could expect to see the updated package on conda-forge (it's been a while). Thanks!
